### ISSUE TITLE
Error When Date-Bounding Region

### ISSUE THREAD

**Issue by ElizabethP712** [emiliom/squid-dinosip#1]
### Part 1:

As we discussed yesterday, I tried to bound the argopy.region command by dates that would encompass inactivate floats as well as active ARGO floats:

`argo_loader.region([-147, -138, 24, 36, 0, 10000, '1999-01-01', '2023-01-01']).load()`
 `argo_loader`
 `argo_loader.plot('trajectory', set_global=True)`

But I got the following errors:
![P1Inactive-ActiveFloatsRegionError](https://github.com/emiliom/squid-dinosip/assets/121905452/f88eb1ca-46ac-42a2-9f48-a26dfc3bc123)
![P2Inactive-ActiveFloatsRegionError](https://github.com/emiliom/squid-dinosip/assets/121905452/4cbcae7c-0d35-4b86-8c26-a2b752a58ea4)

It looks like the issue might have to do with nan data? I feel like I also read somewhere that the min and max dates had to be a smaller margin (like within the same year) so perhaps they do not represent float launch dates but something else?

**MOVED THIS PART TO #2**
~~### Part 2:~~
~~Also, I was hoping to upload some of my Jupyter Lab notebooks that I have been making for this project to this repo (it might be easier to reference coding problems). Would I do that in the Code and files tab as an upload, or git push? Currently I cannot upload any files of my own because it says that feature is disabled if that has anything to do with this too.~~

**Comment by emiliom** [comment]
Sorry for the lag in responding. I ran a series of tests, then got pulled in other directions.

I wasn't able to reproduce your error, so I don't know what's going on. But:

Assuming you grabbed the code from AOS Lesson 32, note that before the `argo_loader.region` statement, this statement is run: `argo_loader = ArgoDataFetcher(src='argovis', parallel=True)`. The lesson doesn't explain why they're using `src='argovis'`, but the argovis source is more limited than the default erddap source; the main reason is that [argovis limits data to the highest quality control flag (QC = 1)](https://argopy.readthedocs.io/en/latest/data_sources.html). When I tested your region search with src=argovis, it was taking a long time so I killed it. I switched to src=erddap. It also takes a long time, but it completed the request. However, there was something wrong with it:

  ![image](https://github.com/emiliom/squid-dinosip/assets/742403/7d9f16a2-6137-4a9d-aca6-2995077b838b)

It returned data only from a portion of 2002. But when I previously ran a region query limiting the start date to 2022-01-01, it returned data from 2022! I don't know why this is happening, but what's clear is that a region search that is very broad (large geographical and temporal windows) may return a ton of data, which will be slow, may freeze, etc. BTW, I didn't find any statements saying that only a limited time window can be requested at a time. Do you remember where you saw it?

The rabbit hole I ended up pursuing was the medata / "index" fetchers, https://argopy.readthedocs.io/en/latest/metadata_fetching.html. They don't return the **data** proper, but rather a lightweight catalog of what floats meet the search criteria. The steps are:

```python
from argopy import IndexFetcher as ArgoIndexFetcher
idx = ArgoIndexFetcher(src='erddap').region([-147, -138, 24, 36, '1999-01-01', '2023-01-01']).load()
```

Then you can view the table (Pandas DataFrame) that's returned, using `idx.index`. Here's a tiny bit preview:

![image](https://github.com/emiliom/squid-dinosip/assets/742403/2507fc18-47bc-4240-9090-9bd6ec751e80)

**Comment by ElizabethP712** [comment]
This was helpful! I am not sure what I did, but I am no longer getting the same error too. Things are just taking a little while to run. I am also currently experimenting with the other options you gave me (i.e. using an Index Fetcher, and checking if I am running into the same issue you did with the 2002 data).

**Comment by ElizabethP712** [comment]
So I was able to get the Index fetching to work after some difficulties! I was also able to get more floats within the SMILE temporal bounds that are both inactive and active and span 2002-2023. I think there is something with the date distinction/bounds that glitches the system, because I was able to reproduce the issue you were having where it only provided data from 2003-2003. There are still two missing floats in the long list of floats that I handpicked, but I can individually investigate those a little easier than if I was missing all but two of my hand-picked floats (which I will do tomorrow). Some of these errors were also weird because I feel like they pop up randomly sometimes but when I re-run the kernal (or the cell individually) it outputs what I want. 

I will upload what I have when I get some time tomorrow morning. Thanks for the aide!

**Comment by emiliom** [comment]
Nice work! Weird behavior on the part of the query results.
