### ISSUE TITLE
Poster Presentation Ouline

### ISSUE THREAD

**Issue by ElizabethP712** [emiliom/squid-dinosip#11]
# Poster Ouline - Any feedback?

As promised, here is the outline for the sections/visuals I intend on including in my poster!

### _Title__:
Still a work in progress, I want to make it more flashy.

### _Authors_:
Elizabeth Pawelka, Emilio Mayorga, James Girton, Zoltan Szuts 

### _Abstract_:
Amanda recommended we include this considering the audience will not have access to this as a hand-out like at many other conferences.

### _Main Takeaway_:
Something about CTD & velocity data and the benefits of ARGO and EM-APEX data being interconnected.

### _Introduction_:

I was thinking here I would go into the brief comparison of pros and cons between ARGO and EM-APEX floats (deployment cycles, locations, velocity measurements, main objectives). The visuals I will include are the deployment map of ARGO (with the location I am focused on circled, something I will just do in PowerPoint), a simple diagram of the components of a general profiling float, and a diagram of the profiling cycle.

I was also thinking this is where I should give a brief definition of the "mixed layer" and salt fingers.

### _Project Goals/Purpose_:
Includes some iteration of the following
1. Better understand the implications of EM-APEX and ARGO data on each other
2. To look at T/S diagrams and CTD diagrams of ARGO floats w/ the same temporal bounds in 2017 and determine what month the mixed layer increases and decreases significantly (the specific case I will focus on for the poster is Region 2, that had the eddy, from EM-APEX data).
3. To look at T/S diagrams and CTD diagrams of the same ARGO floats that intersect Region 2 and see if there are any corresponding step functions in the CTD data that imply warm and salty water is on cold and fresh water.
4. To provide EM-APEX data as a "zoom in" of one particular month of the ARGO data, to compare (and namely display the fact that EM-APEX data gives higher resolution, or more data, for our supposed "mixed layer").
5. To also show what an eddy signature looks like in EM-APEX data (specific to CTD and TS cycle), and determine whether that has been noted by ARGO data.
6. Finally, to compare the velocity calculation and standard deviation of the ARGO float that best aligns with this eddy and see how that compares to the velocity the EM-APEX data actually collected.

#### **Question 2 =This is something I am not entirely sure how I want to portray, but I was thinking some sort of flow diagram of my process? But also, how technical should this be?**

1. Access public database of ARGO data + refine search (not to mention finding the best way to refine my search)
2. Access and re-structure ANDRO data into something easier to access
3. Access and re-structure EM-APEX data into something easier to utalize
5. Make an automated for loop to plot CTD, T/S, trajectory plots
6. Finally, compare all these graphs with a visual once-over!

### _Results_:

Of course, I will be simplifying this down, but I think this is enough "results" and specific comparisons to make with relatively few graphic visuals which will include:

- 1 trajectory plot of the focus ARGO float and SMILE bounded region
- Either two CTD plots and/or two T/S Diagrams of the ARGO float that show a difference in the mixed layer, then the EM-APEX and T/S diagram of that carrot-ed to the side via PowerPoint.
- One velocity plot comparing that of the ARGO float and that of the EM-APEX float (which I will add if I have time after these other comparisons).

### _Conclusions/Future Work_:
-I would continue to make the same general visual once-overs for interesting cases for the rest of the SMILE experiment, and other EM-APEX experiments like DIMES and NISKINE.
-Develop an algorithm or search for a current one to find salt finger signatures and the mixed layer (in other words, automate the process), as well as for velocity comparisons between ANDRO and EM-APEX
-I focused on a month by month basis and overall; but what about historical comparisons? How has CTD data and velocities changed over a longer period of time?

### _References & Acknowledgements_:

“ These data were collected and made freely available by the International Argo Program and the national programs that contribute to it.  (https://argo.ucsd.edu,  [https://www.ocean-ops.org](https://www.ocean-ops.org/board/?t=argo)).  The Argo Program is part of the Global Ocean Observing System. “

*I will follow these steps more closely to give ARGO the recognition it deserves from this [website](https://argo.ucsd.edu/data/acknowledging-argo/) 

#### **Question 3 = Who else should I reference/acknowledge?**

(What are the grants that made this research possible? Do I mention APL here in addition to providing a UW-APL logo on the top of the poster?)

**Comment by emiliom** [comment]
> Question 1 = Is there anyone else I should recognized as a part of the team in this project?

No, no need for anyone else. 

> Question 3 = Who else should I reference/acknowledge?

(What are the grants that made this research possible? Do I mention APL here in addition to providing a UW-APL logo on the top of the poster?)

Gosh. Well, definitely mention clearly that your work was part of the DINO-SIP internship. Ask Amanda for standard text and acknowledgment about that (a UW-APL program funded by the Navy). SQUID is funded by NSF. That's all that's needed.
