### ISSUE TITLE
Matplotlib Plotting Title Question

### ISSUE THREAD

**Issue by ElizabethP712** [emiliom/squid-dinosip#3]
I believe the ARGO School Online was a little misleading in their titles of the two CTD graphs made (one was of temperature to pressure, and I belive the other was of salinity to pressure, but both were labeled as "Temperature In Situ ITS-90 Scale" which to me meant temperature on site 90 degrees to a geographic location (meaning a vertical profile), but perhaps I was wrong in this interpretation. Either way, I believe the second plot was of salinity rather than temperature based on the data being plotted.

Either way, I ran into a question regarding titles, as I am not entirely sure how to phrase it so I get my answer based on documentation. What I have done is turned the plotting into a for-loop so I expedite the process, and I want to include which ID the graph is pulling from the array in the for loop in addition to either pulling some information from the online database of ARGO data or including my own string of a title. How would I combine these features?

Here is what I have so far:

In general my base code looks like this:
![PlottingCTDBaseCode](https://github.com/emiliom/squid-dinosip/assets/121905452/d8e05f31-416f-4208-a06a-6a6e197a4c9f)

Which Results In This:
![BaseCodeResult](https://github.com/emiliom/squid-dinosip/assets/121905452/843cbda1-c57b-46ff-874c-16b404fda400)

1. ID + My Own String
How would I alter this:
`ax[0].set_ylabel(data['PRES'].attrs['long_name'])`
To include units of pressure, or my own chosen words?

2. ID + Title pulled from ARGO Data
How would I alter this:
`ax[0].set_title(a)`
To include both the ID from my array of the for loop and a chosen string of additional words?

**Comment by emiliom** [comment]
> ID + My Own String
How would I alter this:
`ax[0].set_ylabel(data['PRES'].attrs['long_name'])`
To include units of pressure, or my own chosen words?

`set_ylabel` just expects a string. So, you need to compose your own string the way you want it. For example:
`ax[0].set_ylabel(data['PRES'].attrs['long_name'] + " (dbar)")`
or, using a syntax that's often more readable and flexible:
`ax[0].set_ylabel(f"{data['PRES'].attrs['long_name']} (dbar)")`

Now using the units attribute:
`ax[0].set_ylabel(f"{data['PRES'].attrs['long_name']} ({data['PRES'].attrs['units']})")`

> ID + Title pulled from ARGO Data
How would I alter this:
ax[0].set_title(a)
To include both the ID from my array of the for loop and a chosen string of additional words?

Same as above. `a` is a string. So, you just need to compose that string to your liking. 

Here's a tutorial: https://realpython.com/python-string-formatting/

**Comment by emiliom** [comment]
> Either way, I believe the second plot was of salinity rather than temperature based on the data being plotted.

Yup

**Comment by ElizabethP712** [comment]
Okay, awesome. I have gotten it to work now! Thank you.
