### ISSUE TITLE
ANDRO data

### ISSUE THREAD

**Issue by emiliom** [emiliom/squid-dinosip#5]
I took a peek at the [ANDRO](https://www.seanoe.org/data/00360/47077/) data file `ANDRO-91950.dat`. Here are the first 4 rows:
```bash
$ head -n 4 ANDRO-91950.dat
-999.9999 -99.9999 1056.7   4.123 -99.999 -9999.999 -999.99 -999.99 -999.99 -999.99  -14.3115  -7.5940  1537.610  -27.50  -44.39 -999.99 -999.99 -999.9999 -99.9999 -9999.999 -999.99 -999.99 -999.99 -999.99 -999.9999 -99.9999 -9999.999  -14.3040  -7.5820  1537.575  -14.3360  -7.6670  1537.999     3 1900263   1   1
 -14.3830  -7.7475 1047.9   4.162 -99.999  1542.762   -1.26   -2.16 -999.99 -999.99  -14.4377  -7.8190  1547.576  -42.73  -15.75   28.72   48.14  -14.4565  -7.8205  1547.945    5.50  -20.37 -999.99 -999.99  -14.3360  -7.6670  1537.999  -14.4300  -7.8280  1547.526  -14.4550  -7.8260  1547.980     5 1900263   2   2
 -14.4295  -7.8200 1041.3   4.209 -99.999  1552.838    0.67    0.16 -999.99 -999.99 -999.9999 -99.9999 -9999.999 -999.99 -999.99 -999.99 -999.99  -14.4275  -7.7815  1557.995    9.32   -1.88 -999.99 -999.99  -14.4550  -7.8260  1547.980  -14.4040  -7.8140  1557.696  -14.4250  -7.7820  1558.029     3 1900263   3   3
 -14.5445  -7.9240 1039.2   4.189 -99.999  1562.824   -3.18   -3.79    0.03    0.21  -14.6670  -8.0585  1567.653  -11.03   27.84 -999.99 -999.99  -14.7170  -8.0360  1567.977  -25.80   14.89 -999.99 -999.99  -14.4250  -7.7820  1558.029  -14.6640  -8.0660  1567.618  -14.7240  -8.0320  1568.012     4 1900263   4   4
```

The data are column-delimited (see how the columns align across rows), but it looks like it can also be read as space-delimited. I'll try to read, and look at the data document, over the weekend.

**Comment by emiliom** [comment]
This Pandas statement will read all the columns and assign them an incremental integer column header name, base 0 (ie, 0, 1, 2, ...)

```python
df = pd.read_csv("ANDRO-91950.dat", sep='\s+', header=None, nrows=10)
```

To read only a set of columns based on their column index (position), again base 0:
```python
col_idx = [0,1,5,35,36]
df = pd.read_csv("ANDRO-91950.dat", sep='\s+', header=None, nrows=10)[col_idx]
```

You can then use `df.rename()` to assign the final column names:
```python
df.rename(columns={0:"x", 1:"y", 5:"z", 35:"a", 36:"b"}, inplace=True)
```

That should be all you need! And remember to remove the `nrows` argument once you're ready to read all the data.

**Comment by ElizabethP712** [comment]
Wow, I was very much so over-complicating this. I had elements of each step in my code, but had not quite figured out how to get them all to work so simplistically (I think my downfall was trying to split an already existing column into separate columns that represented each element of all the rows after reading the file). I was having a hard time finding the answer online too, but perhaps I wasn't asking the right questions.

Thank you so much! All the data is working now.

**Comment by emiliom** [comment]
Wonderful! Live and learn :smile:
